#+title: Routine Connector
Ziel des Routine Connector ist es, Forschungsdatensätze mit Daten aus der Routineversorgung für eingewilligte Patienten*innen anzureichern. Als Basis dafür, wird auf die im Rahmen der  [[https://www.medizininformatik-initiative.de/][Medizininformatik-Initiative]] (MII) an den Universitätskliniken etablierten Komponenten und Schnittstellen zugegriffen.
Ähnlich zum Routine Connector wurde bisher in den Konzepten der MII vorgesehen, dass Projektdaten zusammen mit einem Projektspezifischen Pseudonym exportiert werden können. Der Hauptunterschied hierbei ist, dass im Routine Connector auch ein Linkage mit den Forschungsdatensätze vorgesehen ist, während die MII Schnittstelle diesen Aspekt außen vorlässt. Da auch das Broad Consent der MII so ein Linkage nicht vorsieht, ist es Aufgabe der durchführenden Projekte, sich einen entsprechenden Consent bei den Patienten einzuholen.
* Benötigte Schnittstellen an den Standorten
Für die Durchführung des Linkages sind Schnittstellen notwendig, die in dieser Form bisher noch nicht im Rahmen der MII genutzt wurden, von denen aber anzunehmen ist, dass diese bereits in großen Teilen vorhanden sind. Im Folgenden werden diese Schnittstellen kurz benannt:
- Beantragen eines neuen Projektpseudonyms und verlinkung mit bereits vorhandenen Patienten auf Basis von im Projekt erhobenen IDAT (Instituts-TTP)
- Abfrage von Patientenpseudonymen auf Basis eines bereits bekannten Pseudonyms
- Speicherung von Einwilligung im [[https://www.hl7.org/fhir/R4/consent.html][HL7-FHIR Consent Format]]
- Abfragen von Einwilligungen im [[https://www.hl7.org/fhir/R4/consent.html][HL7-FHIR Consent Format]]
* Konfigurationsparameter
Der Routine Connector benötigt immer folgende Parameter in der Konfiguration
#+PROPERTY: header-args :var
#+PROPERTY: header-args+ INSTITUTE_TTP_INTERFACE="http://localhost:8081/fhir"
#+PROPERTY: header-args+ ROUTINE_CONNECTOR_API_KEY="routine-connector-password"
| Variable                  | Beispiel                   | Beschreibung                                                  |
| INSTITUTE_TTP_INTERFACE   | http://localhost:8081/fhir | Adresse der Schnittstelle der lokalen Instituts-TTP           |
| ROUTINE_CONNECTOR_API_KEY | routine-connector-password | Schlüssel zur Authentifizierung bei der lokalen Instituts-TTP |
Zusätzlich müssen pro Projekt die folgenden Parameter benannt werden:
#+PROPERTY: header-args+ CONSENT_FHIR_INTERFACE="http://localhost:8085/fhir"
#+PROPERTY: header-args+ MDAT_FHIR_INTERFACE="http://localhost:8086/fhir"
#+PROPERTY: header-args+ PROJECT_FHIR_INTERFACE="http://localhost:8095/fhir"
| Variable               | Beispiel                   | Beschreibung |
| CONSENT_FHIR_INTERFACE | http://localhost:8085/fhir |              |
| MDAT_FHIR_INTERFACE    | http://localhost:8086/fhir |              |
| PROJECT_FHIR_INTERFACE | http://localhost:8095/fhir |              |
* Funktionsweise
** 1) Anfrage von Daten
Um Daten bei der Transferstelle abzufragen muss der Routine Connector den Consent eines Patienten als Beweis für die Einwilligung in die Übermittlung von Daten vorlegen. Dieser wird sowohl in der Standort TTP als auch im Consent Fhir Server hinterlegt.
Die Funktionen der Stand
*** 1.1) Erzeugung Projektpseudonym (Mainzelliste)
Zu Beginn erzeugt der Routine Connector bei der Standort-TTP (in diesem Fall eine Mainzelliste) ein neues Projekt bezogenes Patientenpseudonym.
#+NAME: patient-fhir-data
#+begin_src restclient :results value
POST :INSTITUTE_TTP_INTERFACE/Patient
Content-Type: application/fhir+json
mainzellisteApiKey: :ROUTINE_CONNECTOR_API_KEY

{
    "id": "1",
    "resourceType": "Patient",
    "name": [
        {
            "family": "Timberlake",
            "given": [ "Justin" ],
            "prefix": ["Mr."],
            "use": "official"
        }
    ],
    "birthDate": "1981-01-31",
    "identifier": [
        {
            "use": "secondary",
            "system": "PROJECT_1_ID"
        },
        {
            "use": "temp",
            "system": "SESSION_ID"
        }
    ]
}
#+end_src
Als Antwort erhält der Routine Connector die vollständige FHIR-Resource mit dem neu angelegten Pseudonym
#+RESULTS: patient-fhir-data
#+begin_example
{
  "resourceType": "Patient",
  "id": "0003Y0WZ",
  "identifier": [
    {
      "use": "secondary",
      "system": "PROJECT_1_ID",
      "value": "7LCJA1AP"
    },
    {
      "use": "secondary",
      "system": "INTERNAL_ID",
      "value": "0003Y0WZ"
    },
    {
      "use": "secondary",
      "system": "SESSION_ID",
      "value": "00VNY0RG"
    }
  ],
  "name": [
    {
      "use": "official",
      "family": "Timberlake",
      "given": [
        "Justin"
      ]
    }
  ],
  "birthDate": "1981-01-31"
}
#+end_example
{
  "resourceType": "Patient",
  "id": "0003Y0WZ",
  "identifier": [
    {
      "use": "secondary",
      "system": "PROJECT_1_ID",
      "value": "7LCJA1AP"
    },
    {
      "use": "secondary",
      "system": "INTERNAL_ID",
      "value": "0003Y0WZ"
    },
    {
      "use": "secondary",
      "system": "SESSION_ID",
      "value": "00VNY0RG"
    }
  ],
  "name": [
    {
      "use": "official",
      "family": "Timberlake",
      "given": [
        "Justin"
      ]
    }
  ],
  "birthDate": "1981-01-31"
}
*** 1.2) Extraktion Daten aus Antwort TTP
Der Routine Connector meldet das Consent mit dem von der TTP erhaltenen Identifier an den Consent FHIR-Server. Der dafür Notwendige Session Identifier lässt sich aus der TTP Antwort extrahieren
#+NAME: session-id-from-fhir
#+begin_src sh :var data=patient-fhir-data
echo "$data" | jq -c '[.identifier[] | select(.system | contains("SESSION_ID")) | .value][0]'
#+end_src

#+RESULTS: session-id-from-fhir
: 00VNY0RG

Neben dem Session Identifier lädt der Routine Connector ebenfalls die Projekt ID aus der TTP Antwort. Diese wird aber nicht mit an den FHIR Server übermittelt, um eine ungewollte Zusammenführung von Projektdaten durch die Transferstelle zu verhindern.
#+NAME: project-id-from-fhir
#+begin_src sh :var data=patient-fhir-data
echo "$data" | jq -c '[.identifier[] | select(.system | contains("PROJECT_1_ID")) | .value][0]'
#+end_src

#+RESULTS: project-id-from-fhir
: 7LCJA1AP
*** TODO 1.3) Dokumentation des Consents in Standort-TTP
Das Consent des Patienten wird zu Dokumentationszwecken auch in der Standort-TTP hinterlegt. Der Routine Connector erhält die FHIR Resource hierfür als Input und ergänzt nur den bereits aus 1.2 bekannten Session Identifier.
#+begin_src restclient :var session_id=session-id-from-fhir
POST :INSTITUTE_TTP_INTERFACE/Consent
Content-Type: application/fhir+json

{
    "id": "1",
    "resourceType": "Consent",
    "status": "active",
    "scope": {
        "coding": [
            {
                "system": "http://terminology.hl7.org/CodeSystem/consentscope",
                "code": "research"
            }
        ]
    },
    "category": [
        {
            "coding": [
                {
                    "system": "http://loinc.org",
                    "code": "57016-8"
                }
            ]
        }
    ],
    "patient": {
        "identifier": {
            "system": "SESSION_ID",
            "value": ":session_id"
        }
    },
    "dateTime": "2020-01-01",
    "organization": [
        {
            "display": "Some University Clinic"
        }
    ],
    "policy": [
        {
            "uri": "/Questionnaire/Mii-Broad-Consent"
        }
    ],
    "policyRule": {
        "extension": [
            {
                "url": "http://fhir.de/ConsentManagement/StructureDefinition/Xacml",
                "valueBase64Binary": "TUlJIEJDIEV4YW1wbGUgWEFDTUw="
            }
        ],
        "text": "siehe eingebettetes XACML"
    },
    "provision": {
        "type": "permit",
        "period": {
            "start": "2020-09-01",
            "end": "2050-08-31"
        },
        "provision": [
            {
                "type": "permit",
                "period": {
                    "start": "2020-09-01",
                    "end": "2025-08-31"
                },
                "code": [
                    {
                        "coding": [
                            {
                                "system": "urn:oid:2.16.840.1.113883.3.1937.777.24.5.3",
                                "code": "2.16.840.1.113883.3.1937.777.24.5.3.6",
                                "display": "MDAT_erheben"
                            }
                        ]
                    }
                ]
            },
            {
                "type": "permit",
                "period": {
                    "start": "2020-09-01",
                    "end": "2050-08-31"
                },
                "code": [
                    {
                        "coding": [
                            {
                                "system": "urn:oid:2.16.840.1.113883.3.1937.777.24.5.3",
                                "code": "2.16.840.1.113883.3.1937.777.24.5.3.7",
                                "display": "MDAT_speichern_verarbeiten"
                            }
                        ]
                    }
                ]
            },
            {
                "type": "permit",
                "period": {
                    "start": "2020-09-01",
                    "end": "2050-08-31"
                },
                "code": [
                    {
                        "coding": [
                            {
                                "system": "urn:oid:2.16.840.1.113883.3.1937.777.24.5.3",
                                "code": "2.16.840.1.113883.3.1937.777.24.5.3.8",
                                "display": "MDAT_wissenschaftlich_nutzen_EU_DSGVO_NIVEAU"
                            }
                        ]
                    }
                ]
            },
            {
                "type": "permit",
                "period": {
                    "start": "2020-09-01",
                    "end": "2025-08-31"
                },
                "code": [
                    {
                        "coding": [
                            {
                                "system": "urn:oid:2.16.840.1.113883.3.1937.777.24.5.3",
                                "code": "2.16.840.1.113883.3.1937.777.24.5.3.19",
                                "display": "BIOMAT_erheben"
                            }
                        ]
                    }
                ]
            },
            {
                "type": "permit",
                "period": {
                    "start": "2020-09-01",
                    "end": "2050-08-31"
                },
                "code": [
                    {
                        "coding": [
                            {
                                "system": "urn:oid:2.16.840.1.113883.3.1937.777.24.5.3",
                                "code": "2.16.840.1.113883.3.1937.777.24.5.3.20",
                                "display": "BIOMAT_lagern_verarbeiten"
                            }
                        ]
                    }
                ]
            },
            {
                "type": "permit",
                "period": {
                    "start": "2020-09-01",
                        "end": "2050-08-31"
                    },
                    "code": [
                        {
                            "coding": [
                                {
                                    "system": "urn:oid:2.16.840.1.113883.3.1937.777.24.5.3",
                                    "code": "2.16.840.1.113883.3.1937.777.24.5.3.22",
                                    "display": "BIOMAT_wissenschaftlich_nutzen_EU_DSGVO_NIVEAU"
                                }
                            ]
                        }
                    ]
                }
            ]
        }
}
#+end_src

#+RESULTS:
#+BEGIN_SRC html
<!doctype html><html lang="en"><head><title>HTTP Status 404 – Not Found</title><style type="text/css">body {font-family:Tahoma,Arial,sans-serif;} h1, h2, h3, b {color:white;background-color:#525D76;} h1 {font-size:22px;} h2 {font-size:16px;} h3 {font-size:14px;} p {font-size:12px;} a {color:black;} .line {height:1px;background-color:#525D76;border:none;}</style></head><body><h1>HTTP Status 404 – Not Found</h1><hr class="line" /><p><b>Type</b> Status Report</p><p><b>Message</b> Not Found</p><p><b>Description</b> The origin server did not find a current representation for the target resource or is not willing to disclose that one exists.</p><hr class="line" /><h3>Apache Tomcat/10.1.15</h3></body></html>
<!-- POST http://localhost:8081/fhir/Consent -->
<!-- HTTP/1.1 404  -->
<!-- Server: Mainzelliste/1.12.0 -->
<!-- Content-Type: text/html;charset=utf-8 -->
<!-- Content-Language: en -->
<!-- Content-Length: 714 -->
<!-- Date: Fri, 22 Mar 2024 10:53:53 GMT -->
<!-- Keep-Alive: timeout=20 -->
<!-- Connection: keep-alive -->
<!-- Request duration: 0.008487s -->
#+END_SRC

Der zurückgegebene Consent enthält als Identifier des dazugehörigen Patient nur die SESSION_ID, wodurch die Transferstelle später nicht die Projekt ID ermitteln kann.
*** 1.4) Meldung des Consent an die Inbox
Nach dem Melden des Consent an die TTP wird dieser ebenfalls an den Consent FHIR-Server übermittelt und wird somit auch der Transferstelle bekannt gemacht
#+begin_src restclient :var session_id=session-id-from-fhir
POST :CONSENT_FHIR_INTERFACE/Consent
Content-Type: application/fhir+json

{
    "id": "1",
    "resourceType": "Consent",
    "status": "active",
    "scope": {
        "coding": [
            {
                "system": "http://terminology.hl7.org/CodeSystem/consentscope",
                "code": "research"
            }
        ]
    },
    "category": [
        {
            "coding": [
                {
                    "system": "http://loinc.org",
                    "code": "57016-8"
                }
            ]
        }
    ],
    "patient": {
        "identifier": {
            "system": "SESSION_ID",
            "value": ":session_id"
        }
    },
    "dateTime": "2020-01-01",
    "organization": [
        {
            "display": "Some University Clinic"
        }
    ],
    "policy": [
        {
            "uri": "/Questionnaire/Mii-Broad-Consent"
        }
    ],
    "policyRule": {
        "extension": [
            {
                "url": "http://fhir.de/ConsentManagement/StructureDefinition/Xacml",
                "valueBase64Binary": "TUlJIEJDIEV4YW1wbGUgWEFDTUw="
            }
        ],
        "text": "siehe eingebettetes XACML"
    },
    "provision": {
        "type": "permit",
        "period": {
            "start": "2020-09-01",
            "end": "2050-08-31"
        },
        "provision": [
            {
                "type": "permit",
                "period": {
                    "start": "2020-09-01",
                    "end": "2025-08-31"
                },
                "code": [
                    {
                        "coding": [
                            {
                                "system": "urn:oid:2.16.840.1.113883.3.1937.777.24.5.3",
                                "code": "2.16.840.1.113883.3.1937.777.24.5.3.6",
                                "display": "MDAT_erheben"
                            }
                        ]
                    }
                ]
            },
            {
                "type": "permit",
                "period": {
                    "start": "2020-09-01",
                    "end": "2050-08-31"
                },
                "code": [
                    {
                        "coding": [
                            {
                                "system": "urn:oid:2.16.840.1.113883.3.1937.777.24.5.3",
                                "code": "2.16.840.1.113883.3.1937.777.24.5.3.7",
                                "display": "MDAT_speichern_verarbeiten"
                            }
                        ]
                    }
                ]
            },
            {
                "type": "permit",
                "period": {
                    "start": "2020-09-01",
                    "end": "2050-08-31"
                },
                "code": [
                    {
                        "coding": [
                            {
                                "system": "urn:oid:2.16.840.1.113883.3.1937.777.24.5.3",
                                "code": "2.16.840.1.113883.3.1937.777.24.5.3.8",
                                "display": "MDAT_wissenschaftlich_nutzen_EU_DSGVO_NIVEAU"
                            }
                        ]
                    }
                ]
            },
            {
                "type": "permit",
                "period": {
                    "start": "2020-09-01",
                    "end": "2025-08-31"
                },
                "code": [
                    {
                        "coding": [
                            {
                                "system": "urn:oid:2.16.840.1.113883.3.1937.777.24.5.3",
                                "code": "2.16.840.1.113883.3.1937.777.24.5.3.19",
                                "display": "BIOMAT_erheben"
                            }
                        ]
                    }
                ]
            },
            {
                "type": "permit",
                "period": {
                    "start": "2020-09-01",
                    "end": "2050-08-31"
                },
                "code": [
                    {
                        "coding": [
                            {
                                "system": "urn:oid:2.16.840.1.113883.3.1937.777.24.5.3",
                                "code": "2.16.840.1.113883.3.1937.777.24.5.3.20",
                                "display": "BIOMAT_lagern_verarbeiten"
                            }
                        ]
                    }
                ]
            },
            {
                "type": "permit",
                "period": {
                    "start": "2020-09-01",
                        "end": "2050-08-31"
                    },
                    "code": [
                        {
                            "coding": [
                                {
                                    "system": "urn:oid:2.16.840.1.113883.3.1937.777.24.5.3",
                                    "code": "2.16.840.1.113883.3.1937.777.24.5.3.22",
                                    "display": "BIOMAT_wissenschaftlich_nutzen_EU_DSGVO_NIVEAU"
                                }
                            ]
                        }
                    ]
                }
            ]
        }
}
#+end_src

#+RESULTS:
#+BEGIN_SRC js
{
  "patient": {
    "identifier": {
      "system": "SESSION_ID",
      "value": "00VNY0RG"
    }
  },
  "category": [
    {
      "coding": [
        {
          "system": "http://loinc.org",
          "code": "57016-8"
        }
      ]
    }
  ],
  "provision": {
    "provision": [
      {
        "type": "permit",
        "code": [
          {
            "coding": [
              {
                "system": "urn:oid:2.16.840.1.113883.3.1937.777.24.5.3",
                "code": "2.16.840.1.113883.3.1937.777.24.5.3.6",
                "display": "MDAT_erheben"
              }
            ]
          }
        ],
        "period": {
          "start": "2020-09-01",
          "end": "2025-08-31"
        }
      },
      {
        "type": "permit",
        "code": [
          {
            "coding": [
              {
                "system": "urn:oid:2.16.840.1.113883.3.1937.777.24.5.3",
                "code": "2.16.840.1.113883.3.1937.777.24.5.3.7",
                "display": "MDAT_speichern_verarbeiten"
              }
            ]
          }
        ],
        "period": {
          "start": "2020-09-01",
          "end": "2050-08-31"
        }
      },
      {
        "type": "permit",
        "code": [
          {
            "coding": [
              {
                "system": "urn:oid:2.16.840.1.113883.3.1937.777.24.5.3",
                "code": "2.16.840.1.113883.3.1937.777.24.5.3.8",
                "display": "MDAT_wissenschaftlich_nutzen_EU_DSGVO_NIVEAU"
              }
            ]
          }
        ],
        "period": {
          "start": "2020-09-01",
          "end": "2050-08-31"
        }
      },
      {
        "type": "permit",
        "code": [
          {
            "coding": [
              {
                "system": "urn:oid:2.16.840.1.113883.3.1937.777.24.5.3",
                "code": "2.16.840.1.113883.3.1937.777.24.5.3.19",
                "display": "BIOMAT_erheben"
              }
            ]
          }
        ],
        "period": {
          "start": "2020-09-01",
          "end": "2025-08-31"
        }
      },
      {
        "type": "permit",
        "code": [
          {
            "coding": [
              {
                "system": "urn:oid:2.16.840.1.113883.3.1937.777.24.5.3",
                "code": "2.16.840.1.113883.3.1937.777.24.5.3.20",
                "display": "BIOMAT_lagern_verarbeiten"
              }
            ]
          }
        ],
        "period": {
          "start": "2020-09-01",
          "end": "2050-08-31"
        }
      },
      {
        "type": "permit",
        "code": [
          {
            "coding": [
              {
                "system": "urn:oid:2.16.840.1.113883.3.1937.777.24.5.3",
                "code": "2.16.840.1.113883.3.1937.777.24.5.3.22",
                "display": "BIOMAT_wissenschaftlich_nutzen_EU_DSGVO_NIVEAU"
              }
            ]
          }
        ],
        "period": {
          "start": "2020-09-01",
          "end": "2050-08-31"
        }
      }
    ],
    "type": "permit",
    "period": {
      "start": "2020-09-01",
      "end": "2050-08-31"
    }
  },
  "meta": {
    "versionId": "1",
    "lastUpdated": "2024-03-25T14:25:48.787Z"
  },
  "organization": [
    {
      "display": "Some University Clinic"
    }
  ],
  "resourceType": "Consent",
  "scope": {
    "coding": [
      {
        "system": "http://terminology.hl7.org/CodeSystem/consentscope",
        "code": "research"
      }
    ]
  },
  "policy": [
    {
      "uri": "/Questionnaire/Mii-Broad-Consent"
    }
  ],
  "dateTime": "2020-01-01",
  "status": "active",
  "id": "DDTWADIKWQCFRBVH",
  "policyRule": {
    "extension": [
      {
        "url": "http://fhir.de/ConsentManagement/StructureDefinition/Xacml",
        "valueBase64Binary": "TUlJIEJDIEV4YW1wbGUgWEFDTUw="
      }
    ],
    "text": "siehe eingebettetes XACML"
  }
}
// POST http://localhost:8085/fhir/Consent
// HTTP/1.1 201 Created
// Last-Modified: Mon, 25 Mar 2024 14:25:48 GMT
// ETag: W/"1"
// Location: http://localhost:8080/fhir/Consent/DDTWADIKWQCFRBVH/_history/1
// Content-Type: application/fhir+json;charset=utf-8
// Access-Control-Allow-Origin: *
// Server: Blaze/0.25.0
// Content-Length: 2207
// Request duration: 0.310278s
#+END_SRC

** 2) Bereitstellung von Daten
In diesem Schritt werden von der Datentransferstelle die angeforderten Daten bereitgestellt. Dazu werden die Patientenconsents aus der Inbox geholt und bei der Standort-TTP der zugehörige Identifier in den Routine Systemen ermittelt. Eine Referenzimplementierung wird in der [[file:docs/Referenzimplementierung Transferstelle.org][Dokumentation]] beschrieben.
** 3) Abholen der Daten
In diesem Schritt werden die Daten vom Routine Connector aus der Outbox abgeholt und in der entsprechenden Projekt Datenbank abgelegt.
*** 3.1) Polling von Daten aus der Outbox
Alternative Implementierung könnte mit FHIR Subscriptions umgesetzt werden, aktuell sind diese aber in der Trial Phase, wodurch nicht klar ist welche Server das Feature bereits unterstützten.
Daher wird hier eine Methode basierend auf FHIR Bundles genutzt: https://build.fhir.org/ig/HL7/davinci-ehrx/exchanging-polling.html
#+begin_src restclient :var last-update="2024-03-21"
GET :MDAT_FHIR_INTERFACE/Bundle?_lastUpdated=gt:last-update
Content-Type: application/fhir+json
#+end_src

#+RESULTS:
#+BEGIN_SRC js
{
  "id": "DDTWAMJPERHY5QLN",
  "type": "searchset",
  "entry": [
    {
      "fullUrl": "http://localhost:8080/fhir/Bundle/DDTWALLM5YB5ET5O",
      "resource": {
        "meta": {
          "versionId": "1",
          "lastUpdated": "2024-03-25T14:28:01.474Z"
        },
        "type": "transaction",
        "resourceType": "Bundle",
        "id": "DDTWALLM5YB5ET5O",
        "entry": [
          {
            "request": {
              "method": "POST",
              "url": "/Consent"
            },
            "resource": {
              "patient": {
                "identifier": {
                  "system": "SESSION_ID",
                  "value": "00VNY0RG"
                }
              },
              "category": [
                {
                  "coding": [
                    {
                      "system": "http://loinc.org",
                      "code": "57016-8"
                    }
                  ]
                }
              ],
              "provision": {
                "provision": [
                  {
                    "type": "permit",
                    "code": [
                      {
                        "coding": [
                          {
                            "system": "urn:oid:2.16.840.1.113883.3.1937.777.24.5.3",
                            "code": "2.16.840.1.113883.3.1937.777.24.5.3.6",
                            "display": "MDAT_erheben"
                          }
                        ]
                      }
                    ],
                    "period": {
                      "start": "2020-09-01",
                      "end": "2025-08-31"
                    }
                  },
                  {
                    "type": "permit",
                    "code": [
                      {
                        "coding": [
                          {
                            "system": "urn:oid:2.16.840.1.113883.3.1937.777.24.5.3",
                            "code": "2.16.840.1.113883.3.1937.777.24.5.3.7",
                            "display": "MDAT_speichern_verarbeiten"
                          }
                        ]
                      }
                    ],
                    "period": {
                      "start": "2020-09-01",
                      "end": "2050-08-31"
                    }
                  },
                  {
                    "type": "permit",
                    "code": [
                      {
                        "coding": [
                          {
                            "system": "urn:oid:2.16.840.1.113883.3.1937.777.24.5.3",
                            "code": "2.16.840.1.113883.3.1937.777.24.5.3.8",
                            "display": "MDAT_wissenschaftlich_nutzen_EU_DSGVO_NIVEAU"
                          }
                        ]
                      }
                    ],
                    "period": {
                      "start": "2020-09-01",
                      "end": "2050-08-31"
                    }
                  },
                  {
                    "type": "permit",
                    "code": [
                      {
                        "coding": [
                          {
                            "system": "urn:oid:2.16.840.1.113883.3.1937.777.24.5.3",
                            "code": "2.16.840.1.113883.3.1937.777.24.5.3.19",
                            "display": "BIOMAT_erheben"
                          }
                        ]
                      }
                    ],
                    "period": {
                      "start": "2020-09-01",
                      "end": "2025-08-31"
                    }
                  },
                  {
                    "type": "permit",
                    "code": [
                      {
                        "coding": [
                          {
                            "system": "urn:oid:2.16.840.1.113883.3.1937.777.24.5.3",
                            "code": "2.16.840.1.113883.3.1937.777.24.5.3.20",
                            "display": "BIOMAT_lagern_verarbeiten"
                          }
                        ]
                      }
                    ],
                    "period": {
                      "start": "2020-09-01",
                      "end": "2050-08-31"
                    }
                  },
                  {
                    "type": "permit",
                    "code": [
                      {
                        "coding": [
                          {
                            "system": "urn:oid:2.16.840.1.113883.3.1937.777.24.5.3",
                            "code": "2.16.840.1.113883.3.1937.777.24.5.3.22",
                            "display": "BIOMAT_wissenschaftlich_nutzen_EU_DSGVO_NIVEAU"
                          }
                        ]
                      }
                    ],
                    "period": {
                      "start": "2020-09-01",
                      "end": "2050-08-31"
                    }
                  }
                ],
                "type": "permit",
                "period": {
                  "start": "2020-09-01",
                  "end": "2050-08-31"
                }
              },
              "meta": {
                "versionId": "1",
                "lastUpdated": "2024-03-22T10:54:05.703Z"
              },
              "organization": [
                {
                  "display": "Some University Clinic"
                }
              ],
              "resourceType": "Consent",
              "scope": {
                "coding": [
                  {
                    "system": "http://terminology.hl7.org/CodeSystem/consentscope",
                    "code": "research"
                  }
                ]
              },
              "policy": [
                {
                  "uri": "/Questionnaire/Mii-Broad-Consent"
                }
              ],
              "dateTime": "2020-01-01",
              "status": "active",
              "id": "DDTFZPTVOFVKRGAV",
              "policyRule": {
                "extension": [
                  {
                    "url": "http://fhir.de/ConsentManagement/StructureDefinition/Xacml",
                    "valueBase64Binary": "TUlJIEJDIEV4YW1wbGUgWEFDTUw="
                  }
                ],
                "text": "siehe eingebettetes XACML"
              }
            }
          },
          {
            "request": {
              "method": "POST",
              "url": "/Condition"
            },
            "resource": {
              "clinicalStatus": {
                "coding": [
                  {
                    "system": "http://terminology.hl7.org/CodeSystem/condition-clinical",
                    "code": "active"
                  }
                ]
              },
              "meta": {
                "versionId": "8",
                "lastUpdated": "2024-03-22T13:52:42.493Z"
              },
              "onsetPeriod": {
                "start": "2020-02-26T12:00:00+01:00",
                "end": "2020-03-05T13:00:00+01:00"
              },
              "resourceType": "Condition",
              "recordedDate": "2020-02-26T12:00:00+01:00",
              "id": "DDTGN5W6O3JG7DSN",
              "code": {
                "coding": [
                  {
                    "system": "http://fhir.de/CodeSystem/dimdi/icd-10-gm",
                    "version": "2020",
                    "code": "S50.0",
                    "display": "Prellung des Ellenbogens"
                  },
                  {
                    "system": "http://snomed.info/sct",
                    "code": "91613004",
                    "display": "Contusion of elbow (disorder)"
                  }
                ],
                "text": "Prellung des linken Ellenbogens"
              },
              "subject": {
                "identifier": {
                  "system": "DIZ_ID",
                  "value": "005TY0EC"
                }
              }
            }
          },
          {
            "request": {
              "method": "POST",
              "url": "/Procedure"
            },
            "resource": {
              "category": {
                "coding": [
                  {
                    "system": "http://snomed.info/sct",
                    "code": "387713003",
                    "display": "Surgical procedure (procedure)"
                  }
                ]
              },
              "meta": {
                "versionId": "9",
                "lastUpdated": "2024-03-22T13:56:10.253Z"
              },
              "resourceType": "Procedure",
              "status": "completed",
              "id": "DDTGOKMW4ML7HSCJ",
              "performedDateTime": "2020-04-23",
              "code": {
                "coding": [
                  {
                    "system": "http://snomed.info/sct",
                    "code": "80146002",
                    "display": "Excision of appendix (procedure)"
                  },
                  {
                    "system": "http://fhir.de/CodeSystem/dimdi/ops",
                    "version": "2020",
                    "code": "5-470",
                    "display": "Appendektomie"
                  }
                ]
              },
              "subject": {
                "identifier": {
                  "system": "DIZ_ID",
                  "value": "005TY0EC"
                }
              }
            }
          }
        ]
      },
      "search": {
        "mode": "match"
      }
    }
  ],
  "link": [
    {
      "relation": "first",
      "url": "http://localhost:8080/fhir/Bundle/__page?_lastUpdated=gt2024-03-21&_count=50&__t=1"
    },
    {
      "relation": "self",
      "url": "http://localhost:8080/fhir/Bundle?_lastUpdated=gt2024-03-21&_count=50"
    }
  ],
  "total": 1,
  "resourceType": "Bundle"
}
// GET http://localhost:8086/fhir/Bundle?_lastUpdated=gt2024-03-21
// HTTP/1.1 200 OK
// Link: <http://localhost:8080/fhir/Bundle/__page?_lastUpdated=gt2024-03-21&_count=50&__t=1>;rel="first",<http://localhost:8080/fhir/Bundle?_lastUpdated=gt2024-03-21&_count=50>;rel="self"
// Content-Type: application/fhir+json;charset=utf-8
// Access-Control-Allow-Origin: *
// Server: Blaze/0.25.0
// Content-Length: 4236
// Request duration: 0.047349s
#+END_SRC

*** 3.x) Ergänzen des Projektidentifier
In dem erhaltenen FHIR Bundle ist jetzt überall der Identifier SESSION_ID enthalten. Dieser muss durch den Routine Connector durch PROJECT_1_ID ersetzt werden.
*** 3.2) Laden der Routine Daten in Projektdatenbank
Das Laden der Routine Daten in die Projektdatenbank funktioniert analog zu dem Laden in 2.4. Hierbei ist zu beachten, dass nur die aktuellsten Resourcen an die Projektdatenbank übermittelt werden sollen, da die Anfrage in 3.1 auch mehrmals die gleiche Resource zurückgegeben kann, eben in unterschiedlichen Versionen.
Der Routine Connector baut deshalb vor dem Hochladen der Daten ein FHIR Bundle mit allen relevanten Resourcen zusammen und übermittelt dieses an die Adresse
#+begin_src restclient :var project-id=project-id-from-fhir
POST :PROJECT_FHIR_INTERFACE
Content-Type: application/fhir+json

{
        "meta": {
          "versionId": "1",
          "lastUpdated": "2024-03-25T14:28:01.474Z"
        },
        "type": "transaction",
        "resourceType": "Bundle",
        "id": "DDTWALLM5YB5ET5O",
        "entry": [
          {
            "request": {
              "method": "POST",
              "url": "/Consent"
            },
            "resource": {
              "patient": {
                "identifier": {
                  "system": "PROJECT_1_ID",
                  "value": ":project-id-from-fhir"
                }
              },
              "category": [
                {
                  "coding": [
                    {
                      "system": "http://loinc.org",
                      "code": "57016-8"
                    }
                  ]
                }
              ],
              "provision": {
                "provision": [
                  {
                    "type": "permit",
                    "code": [
                      {
                        "coding": [
                          {
                            "system": "urn:oid:2.16.840.1.113883.3.1937.777.24.5.3",
                            "code": "2.16.840.1.113883.3.1937.777.24.5.3.6",
                            "display": "MDAT_erheben"
                          }
                        ]
                      }
                    ],
                    "period": {
                      "start": "2020-09-01",
                      "end": "2025-08-31"
                    }
                  },
                  {
                    "type": "permit",
                    "code": [
                      {
                        "coding": [
                          {
                            "system": "urn:oid:2.16.840.1.113883.3.1937.777.24.5.3",
                            "code": "2.16.840.1.113883.3.1937.777.24.5.3.7",
                            "display": "MDAT_speichern_verarbeiten"
                          }
                        ]
                      }
                    ],
                    "period": {
                      "start": "2020-09-01",
                      "end": "2050-08-31"
                    }
                  },
                  {
                    "type": "permit",
                    "code": [
                      {
                        "coding": [
                          {
                            "system": "urn:oid:2.16.840.1.113883.3.1937.777.24.5.3",
                            "code": "2.16.840.1.113883.3.1937.777.24.5.3.8",
                            "display": "MDAT_wissenschaftlich_nutzen_EU_DSGVO_NIVEAU"
                          }
                        ]
                      }
                    ],
                    "period": {
                      "start": "2020-09-01",
                      "end": "2050-08-31"
                    }
                  },
                  {
                    "type": "permit",
                    "code": [
                      {
                        "coding": [
                          {
                            "system": "urn:oid:2.16.840.1.113883.3.1937.777.24.5.3",
                            "code": "2.16.840.1.113883.3.1937.777.24.5.3.19",
                            "display": "BIOMAT_erheben"
                          }
                        ]
                      }
                    ],
                    "period": {
                      "start": "2020-09-01",
                      "end": "2025-08-31"
                    }
                  },
                  {
                    "type": "permit",
                    "code": [
                      {
                        "coding": [
                          {
                            "system": "urn:oid:2.16.840.1.113883.3.1937.777.24.5.3",
                            "code": "2.16.840.1.113883.3.1937.777.24.5.3.20",
                            "display": "BIOMAT_lagern_verarbeiten"
                          }
                        ]
                      }
                    ],
                    "period": {
                      "start": "2020-09-01",
                      "end": "2050-08-31"
                    }
                  },
                  {
                    "type": "permit",
                    "code": [
                      {
                        "coding": [
                          {
                            "system": "urn:oid:2.16.840.1.113883.3.1937.777.24.5.3",
                            "code": "2.16.840.1.113883.3.1937.777.24.5.3.22",
                            "display": "BIOMAT_wissenschaftlich_nutzen_EU_DSGVO_NIVEAU"
                          }
                        ]
                      }
                    ],
                    "period": {
                      "start": "2020-09-01",
                      "end": "2050-08-31"
                    }
                  }
                ],
                "type": "permit",
                "period": {
                  "start": "2020-09-01",
                  "end": "2050-08-31"
                }
              },
              "meta": {
                "versionId": "1",
                "lastUpdated": "2024-03-22T10:54:05.703Z"
              },
              "organization": [
                {
                  "display": "Some University Clinic"
                }
              ],
              "resourceType": "Consent",
              "scope": {
                "coding": [
                  {
                    "system": "http://terminology.hl7.org/CodeSystem/consentscope",
                    "code": "research"
                  }
                ]
              },
              "policy": [
                {
                  "uri": "/Questionnaire/Mii-Broad-Consent"
                }
              ],
              "dateTime": "2020-01-01",
              "status": "active",
              "id": "DDTFZPTVOFVKRGAV",
              "policyRule": {
                "extension": [
                  {
                    "url": "http://fhir.de/ConsentManagement/StructureDefinition/Xacml",
                    "valueBase64Binary": "TUlJIEJDIEV4YW1wbGUgWEFDTUw="
                  }
                ],
                "text": "siehe eingebettetes XACML"
              }
            }
          },
          {
            "request": {
              "method": "POST",
              "url": "/Condition"
            },
            "resource": {
              "clinicalStatus": {
                "coding": [
                  {
                    "system": "http://terminology.hl7.org/CodeSystem/condition-clinical",
                    "code": "active"
                  }
                ]
              },
              "meta": {
                "versionId": "8",
                "lastUpdated": "2024-03-22T13:52:42.493Z"
              },
              "onsetPeriod": {
                "start": "2020-02-26T12:00:00+01:00",
                "end": "2020-03-05T13:00:00+01:00"
              },
              "resourceType": "Condition",
              "recordedDate": "2020-02-26T12:00:00+01:00",
              "id": "DDTGN5W6O3JG7DSN",
              "code": {
                "coding": [
                  {
                    "system": "http://fhir.de/CodeSystem/dimdi/icd-10-gm",
                    "version": "2020",
                    "code": "S50.0",
                    "display": "Prellung des Ellenbogens"
                  },
                  {
                    "system": "http://snomed.info/sct",
                    "code": "91613004",
                    "display": "Contusion of elbow (disorder)"
                  }
                ],
                "text": "Prellung des linken Ellenbogens"
              },
              "subject": {
                "identifier": {
                  "system": "DIZ_ID",
                  "value": "005TY0EC"
                }
              }
            }
          },
          {
            "request": {
              "method": "POST",
              "url": "/Procedure"
            },
            "resource": {
              "category": {
                "coding": [
                  {
                    "system": "http://snomed.info/sct",
                    "code": "387713003",
                    "display": "Surgical procedure (procedure)"
                  }
                ]
              },
              "meta": {
                "versionId": "9",
                "lastUpdated": "2024-03-22T13:56:10.253Z"
              },
              "resourceType": "Procedure",
              "status": "completed",
              "id": "DDTGOKMW4ML7HSCJ",
              "performedDateTime": "2020-04-23",
              "code": {
                "coding": [
                  {
                    "system": "http://snomed.info/sct",
                    "code": "80146002",
                    "display": "Excision of appendix (procedure)"
                  },
                  {
                    "system": "http://fhir.de/CodeSystem/dimdi/ops",
                    "version": "2020",
                    "code": "5-470",
                    "display": "Appendektomie"
                  }
                ]
              },
              "subject": {
                "identifier": {
                  "system": "DIZ_ID",
                  "value": "005TY0EC"
                }
              }
            }
          }
        ]
      }
#+end_src

#+RESULTS:
#+BEGIN_SRC js
{
  "id": "DDTWBABWDGLWQZ2Y",
  "type": "transaction-response",
  "entry": [
    {
      "response": {
        "status": "201",
        "location": "http://localhost:8080/fhir/Consent/DDTWBABVJFHEGLWW/_history/2",
        "etag": "W/\"2\"",
        "lastModified": "2024-03-25T14:33:40.444Z"
      }
    },
    {
      "response": {
        "status": "201",
        "location": "http://localhost:8080/fhir/Condition/DDTWBABVJFHEGLWX/_history/2",
        "etag": "W/\"2\"",
        "lastModified": "2024-03-25T14:33:40.444Z"
      }
    },
    {
      "response": {
        "status": "201",
        "location": "http://localhost:8080/fhir/Procedure/DDTWBABVJFHEGLWY/_history/2",
        "etag": "W/\"2\"",
        "lastModified": "2024-03-25T14:33:40.444Z"
      }
    }
  ],
  "resourceType": "Bundle"
}
// POST http://localhost:8095/fhir
// HTTP/1.1 200 OK
// Content-Type: application/fhir+json;charset=utf-8
// Access-Control-Allow-Origin: *
// Server: Blaze/0.25.0
// Content-Length: 588
// Request duration: 0.023219s
#+END_SRC

* Aktuelle Fragen
1) Soll die Inbox persistent sein, d.h. eingefügte Consents werden dauerhaft gespeichert und nicht nach der Übertragung gelöscht?
   Pro: Daten in der Outbox bleiben aktuell --> vor allem bei Einwilligungen für die Nächsten X Jahre sinnvoll
   Contra: Der Identifier Session kann keine Temporär erzeugte ID sein, da diese dann ja ihre Gültigkeit davor verlieren würde
2) Wo wird Token erzeugt?
   Im Routine Connector --> funktioniert nicht, da die Standort TTP das ja nicht verknüpfen kann
   In der TTP --> kann die TTP das überhaupt auflösen?
   ==> Das kann eigentlich nur die TTP erzeugen
3) Soll der Routine Connector mehrere Projektdatenbanken unterstützen?
   Dann wäre eine Konfiguration von Projektidentifier und zugehörigen Projektdatenbanken notwendig.
4) Wie lassen sich alle vorhandenen Daten zum Patienten ermitteln?
   Reicht die Abfrage subject.identifier=DIZ_ID|VALUE? Siehe 2.5
   Abklären ob Funktion 2 überhaupt gewünscht, wenn ja: FHIR Server für ROutine Daten erwarten, fhir search parameter hinzufügen und schnittstelle von ID_Management abfragen
5) Wie sieht bisher die Infrastruktur für ResearchProjekts aus?
   Soweit ich es verstehe soll ein Consent auf ein ResearchProject verweisen. Dieses müsste dann ja mit der Consent Resource übermittelt werden. Einfach als Bundle?
* Roadmap
** Schnittstellen der Greifswald THS ebenfalls überprüfen
