fhir:
  input:
    url: ${FHIR_INPUT_URL:http://localhost:8080/fhir}
  output:
    url: ${FHIR_OUTPUT_URL:http://localhost:8090/fhir}
spring:
  profiles:
    active:
      ${SPRING_PROFILES_ACTIVE:mii2bbmri}