fhir:
  input:
    url: ${FHIR_INPUT_URL:http://localhost:8080/fhir}
  output:
    url: ${FHIR_OUTPUT_URL:http://localhost:8090/fhir}
data:
  outputFileDirectory: ./test
  writeBundlesToFile: false
spring:
  profiles:
    active:
      ${PROFILE:mii2bbmri}
