dist = DHKI callback test Mainzelliste
db.driver = org.postgresql.Driver
db.url = jdbc:postgresql://callback-db:5432/mainzelliste
db.username = mainzelliste
db.password = mainzelliste

field.vorname.type = PlainTextField
field.nachname.type = PlainTextField
field.geburtsname.type = PlainTextField
field.geburtstag.type = IntegerField
field.geburtsmonat.type = IntegerField
field.geburtsjahr.type = IntegerField
field.plz.type = PlainTextField
field.ort.type = PlainTextField

validator.field.vorname.required = true
validator.field.nachname.required = true
validator.field.geburtstag.required = true
validator.field.geburtsmonat.required = true
validator.field.geburtsjahr.required = true
validator.date.0.fields = geburtstag, geburtsmonat, geburtsjahr
validator.date.0.format = ddMMyyyy

exchangeGroup.0 = vorname, nachname, geburtsname
field.vorname.transformers = StringNormalizer, FirstNameDecomposer
field.nachname.transformers = StringNormalizer, GermanLastNameDecomposer
field.geburtsname.transformers = StringNormalizer, GermanLastNameDecomposer
field.vorname.comparator = NGramComparator
field.nachname.comparator = NGramComparator
field.geburtsname.comparator = NGramComparator
field.geburtstag.comparator = BinaryFieldComparator
field.geburtsmonat.comparator = BinaryFieldComparator
field.geburtsjahr.comparator = BinaryFieldComparator
field.plz.comparator = BinaryFieldComparator
field.ort.comparator = NGramComparator
matcher = EpilinkMatcher
matcher.epilink.vorname.frequency = 0.000235
matcher.epilink.nachname.frequency = 0.0000271
matcher.epilink.geburtsname.frequency = 0.0000271
matcher.epilink.geburtstag.frequency = 0.0333
matcher.epilink.geburtsmonat.frequency = 0.0833
matcher.epilink.geburtsjahr.frequency = 0.0286
matcher.epilink.plz.frequency = 0.01
matcher.epilink.ort.frequency = 0.01
matcher.epilink.vorname.errorRate = 0.01
matcher.epilink.nachname.errorRate = 0.008
matcher.epilink.geburtsname.errorRate = 0.008
matcher.epilink.geburtstag.errorRate = 0.005
matcher.epilink.geburtsmonat.errorRate = 0.002
matcher.epilink.geburtsjahr.errorRate = 0.004
matcher.epilink.plz.errorRate = 0.04
matcher.epilink.ort.errorRate = 0.04
matcher.epilink.threshold_match = 0.95
matcher.epilink.threshold_non_match = 0.6

idgenerators = pid, tobesynced
idgenerator.pid = PIDGenerator
idgenerator.pid.k1 = 11
idgenerator.pid.k2 = 12
idgenerator.pid.k3 = 13
idgenerator.pid.eager = *
idgenerator.tobesynced = PIDGenerator
idgenerator.tobesynced.k1 = 21
idgenerator.tobesynced.k2 = 22
idgenerator.tobesynced.k3 = 23
idgenerator.tobesynced.callback.0.url = http://onkostar-push:8082/patients
idgenerator.tobesynced.callback.0.resultIds = tobesynced
idgenerator.tobesynced.callback.0.resultFields = vorname, nachname, geburtsname, geburtstag, geburtsmonat, geburtsjahr, plz, ort
idgenerator.tobesynced.callback.0.headers.apiKey = foobar

experimental.fhir.enable = true
fhir.map.vorname = Patient.name.given
fhir.map.nachname = Patient.name.where(use = 'official').family
fhir.map.geburtsname = Patient.name.where(use = 'maiden').family
fhir.map.date.0 = Patient.birthDate

servers.0.apiKey = pleaseChangeMeToo
servers.0.permissions = createSession;showSessionIds;createToken;tt_addPatient;tt_readPatients;tt_editPatient;tt_createIds;tt_deletePatient;tt_addConsent;tt_readConsent;tt_searchConsents;tt_addConsentTemplate;tt_readConsentTemplate;tt_searchConsentTemplates;tt_addConsentPolicySet;tt_readConsentPolicySet;tt_searchConsentPolicySets;tt_addConsentPolicy;tt_readConsentPolicy;tt_searchConsentPolicies;readConfiguration;fhir_read;fhir_update;fhir_create;fhir_delete;fhir_search
servers.0.allowedRemoteAdresses = 0.0.0.0/0
callback.allowedFormat = http://.*
callback.allowSelfsigned = false
