[env]
# Environment for Routine Connector
TTP_URL="http://localhost:8082"
TTP_ML_API_KEY="transFAIR-password"
FHIR_REQUEST_URL="http://localhost:8085"
# FHIR_REQUEST_CREDENTIALS="user:pw"
FHIR_INPUT_URL="http://localhost:8086"
# FHIR_INPUT_CREDENTIALS="user:pw"
FHIR_OUTPUT_URL="http://localhost:8095"
# FHIR_OUTPUT_CREDENTIALS="user:pw"
DATABASE_URL="sqlite://data_requests.sql"
PROJECT_ID_SYSTEM="PROJECT_1_ID"
EXCHANGE_ID_SYSTEM="SESSION_ID"
RUST_LOG="warn,wip_routine_connector=debug"
no_proxy="localhost"
