[env]
# Environment for Routine Connector
INSTITUTE_TTP_URL="http://localhost:8081"
INSTITUTE_TTP_API_KEY="routine-connector-password"
FHIR_REQUEST_URL="http://localhost:8085"
FHIR_REQUEST_CREDENTIALS="bla"
FHIR_INPUT_URL="http://localhost:8086"
FHIR_INPUT_CREDENTIALS="foo"
FHIR_OUTPUT_URL="http://localhost:8095"
FHIR_OUTPUT_CREDENTIALS="foobar"
DATABASE_URL="sqlite://data_requests.sql"
PROJECT_ID_SYSTEM="PROJECT_1_ID"
EXCHANGE_ID_SYSTEM="SESSION_ID"
RUST_LOG="warn,wip_routine_connector=debug"
no_proxy="localhost"
# Environment for Mainzelliste
ML_DB_PASS="my-secret-db-password"
ML_ROUTINE_CONNECTOR_PASSPHRASE="routine-connector-password"
ML_DIZ_PASSPHRASE="diz-password"
ML_LOG_LEVEL="debug"